import random

#Introduction to the game 
name = input("Enter Your name: ")
print("Lets play a game " ,name)

#This is a list of words
words = ['rainbow', 'computer', 'science', 'programming',
         'python', 'mathematics', 'player', 'condition',
         'reverse', 'water', 'board', 'geeks']

#random word generated by the computer
word_chosen = random.choice(words)

print("Guess the characters")
guesses = ""

#Number of tries you have
turns = random.randint(0,11)

while turns > 0:
    
    failed = 0
    
    #Checks for characters
    for char in word_chosen:
        if char in guesses:
            print(char, end = " ")
        else:
            print("_")
            failed += 1
    
    if failed == 0:
        print("Congratulations You have won!!")
        print("The word is ", word_chosen)
        break
    
    print()
    guess = input("guess a character:")
 
    guesses += guess
 
    if guess not in word_chosen:

        turns -= 1
        print("Wrong")
        
        print("You have", + turns,)
 
        if turns == 0:
            print("You Loose")
    
    
             